# Generated by Django 4.1.7 on 2023-05-03 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airplane_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Boarding_pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boarding_pass_id', models.IntegerField()),
                ('purchase_id', models.IntegerField()),
                ('passenger_id', models.IntegerField()),
                ('seat_type_id', models.IntegerField()),
                ('seat_id', models.IntegerField()),
                ('flight_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_id', models.IntegerField()),
                ('takeoff_date_time', models.IntegerField()),
                ('takeoff_airport', models.CharField(max_length=255)),
                ('landing_data_time', models.IntegerField()),
                ('landing_airport', models.CharField(max_length=255)),
                ('airplane_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_id', models.IntegerField()),
                ('dni', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_id', models.IntegerField()),
                ('purchase_date', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_id', models.IntegerField()),
                ('seat_column', models.CharField(max_length=255)),
                ('seat_row', models.IntegerField()),
                ('seat_type_id', models.IntegerField()),
                ('airplane_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seat_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_type_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
